@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.NjA5ZGNmYTAwNzRhYjIxNmM4OWQ0YTY5.6BhYzzUTXry_3WHE2vVRwihQBXkqrSEnQdsi7zyYZ4g

// -> Videos
GET {{api}}/videos
###
GET {{api}}/videos/609b8bb2f0b7661c3035c5aa
###

// -> Rating
GET {{api}}/rating/609b8bb2f0b7661c3035c5aa/
Cookie: token={{token}}
###
POST {{api}}/rating/609b8bb2f0b7661c3035c5aa/like
Cookie: token={{token}}
###
POST {{api}}/rating/609b8bb2f0b7661c3035c5aa/dislike
Cookie: token={{token}}
###
DELETE {{api}}/rating/609b8bb2f0b7661c3035c5aa
Cookie: token={{token}}

###
// -> Subscription
GET {{api}}/subscription/609b8bb2f0b7661c3035c5a9
Cookie: token={{token}}

###
POST {{api}}/subscription/609b8bb2f0b7661c3035c5a9
Cookie: token={{token}}
###
DELETE {{api}}/subscription/609b8bb2f0b7661c3035c5a9
Cookie: token={{token}}
###

// -> Subscription
GET {{api}}/comment/609b8bb2f0b7661c3035c5a9
###
POST {{api}}/comment/609e868b962a3714d0933195
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "new"
}
###
PATCH  {{api}}/comment/609e7cf2e867e720f40ac476
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Hey307"
}
###
DELETE  {{api}}/comment/609b8bb2f0b7661c3035c5a9
Cookie: token={{token}}
###

# Reply
POST  {{api}}/comment/reply/609e85c65a62cc13541419fd
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Reply Hey307"
}

