@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.MQ.fGaUARI99DDadCuNm4ZUhaB6Bpx8KiJsnCLTisJ0bp4
@videoId = 1
@commentId = 1


// -> Comment
GET {{api}}/comments/{{videoId}}?page=1
Cookie: token={{token}}
###
POST {{api}}/comments/{{videoId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "2033"
}
###
PATCH  {{api}}/comments/122
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "ntnt"
}
###
DELETE  {{api}}/comments/102
Cookie: token={{token}}
###

# -> Comment: Reply
GET {{api}}/comments/{{commentId}}/replies?page=2
###
POST  {{api}}/comments/2/replies
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "This is a SOLID reply to the nicer comment which has done some mutations"
}
