@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.MQ.fGaUARI99DDadCuNm4ZUhaB6Bpx8KiJsnCLTisJ0bp4
@videoId = 1
@commentId = 102


// -> Rating: Video
POST {{api}}/ratings/videos/{{videoId}}/like
Cookie: token={{token}}
###
POST {{api}}/ratings/videos/{{videoId}}/dislike
Cookie: token={{token}}
###
DELETE {{api}}/ratings/videos/{{videoId}}
Cookie: token={{token}}
###

// -> Rating: Comment
POST {{api}}/ratings/comments/{{commentId}}/like
Cookie: token={{token}}
###
POST {{api}}/ratings/comments/{{commentId}}/dislike
Cookie: token={{token}}
###
DELETE {{api}}/ratings/comments/{{commentId}}
Cookie: token={{token}}
###