@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.MQ.fGaUARI99DDadCuNm4ZUhaB6Bpx8KiJsnCLTisJ0bp4
@channelId = 4


GET {{api}}/subscribers/subscriptions
Cookie: token={{token}}
###
POST {{api}}/subscribers/{{channelId}}
Cookie: token={{token}}
###
DELETE {{api}}/subscribers/{{channelId}}
Cookie: token={{token}}
###