@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.MQ.fGaUARI99DDadCuNm4ZUhaB6Bpx8KiJsnCLTisJ0bp4
@channelId = 1

POST {{api}}/subscribers/{{channelId}}
Cookie: token={{token}}
###
DELETE {{api}}/subscribers/{{channelId}}
Cookie: token={{token}}
###