@api = http://localhost:5000
@videoId = 1
@token = eyJhbGciOiJIUzI1NiJ9.MQ.fGaUARI99DDadCuNm4ZUhaB6Bpx8KiJsnCLTisJ0bp4


GET {{api}}/videos
###
GET {{api}}/videos/{{videoId}}
Cookie: token={{token}}
###

GET {{api}}/videos/mine
Cookie: token={{token}}

###

GET {{api}}/history
Cookie: token={{token}}

###
// POST {{api}}/videos 
 

GET {{api}}/watchlater/
Cookie: token={{token}}
###
POST {{api}}/watchlater/1
Cookie: token={{token}}
###
DELETE  {{api}}/watchlater/1
Cookie: token={{token}}
###
GET {{api}}/playlists/liked
Cookie: token={{token}}
