@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.NjA5ZGNmYTAwNzRhYjIxNmM4OWQ0YTY5.6BhYzzUTXry_3WHE2vVRwihQBXkqrSEnQdsi7zyYZ4g
@videoId = 609ea0a48d22892130792200
@commentId = 609f57d744be5320dc98bdc5


// -> Comment
GET {{api}}/comment/{{videoId}}
###
POST {{api}}/comment/{{videoId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "new"
}
###
PATCH  {{api}}/comment/{{commentId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Lookin for graphql"
}
###
DELETE  {{api}}/comment/{{commentId}}
Cookie: token={{token}}
###

# -> Comment: Reply
GET {{api}}/comment/reply/{{commentId}}
###
POST  {{api}}/comment/reply/{{commentId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Reply Hey307"
}
