@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.MQ.fGaUARI99DDadCuNm4ZUhaB6Bpx8KiJsnCLTisJ0bp4
@videoId = 1
@commentId = 1


// -> Comment
GET {{api}}/comments/{{videoId}}
###
POST {{api}}/comments/{{videoId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Hey this is a nicer comment"
}
###
PATCH  {{api}}/comments/{{commentId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Hey this is a nicer comment which has been edited 2nd time"
}
###
DELETE  {{api}}/comments/5
Cookie: token={{token}}
###

# -> Comment: Reply
GET {{api}}/comments/replies/{{commentId}}
###
POST  {{api}}/comments/replies/{{commentId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "This is a SOLID reply to the nicer comment which has done some mutations"
}
