@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.MQ.48rVlWZkUklvo69kDnVzudXUaFjVH1IVU7asr0ia7hI
@videoId = 1
@commentId = 7


// -> Comment
GET {{api}}/comment/{{videoId}}
###
POST {{api}}/comment/{{videoId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Hey this is a nicer comment"
}
###
PATCH  {{api}}/comment/{{commentId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Hey this is a nicer comment which has been edited 2nd time"
}
###
DELETE  {{api}}/comment/5
Cookie: token={{token}}
###

# -> Comment: Reply
GET {{api}}/comment/reply/{{commentId}}
###
POST  {{api}}/comment/reply/{{commentId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "This is a SOLID reply to the nicer comment which has done some mutations"
}
