@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.NQ.7lWaaY_hpcvuiQWjQJCyXxi5V9sSKqQE5KYFsG7TRaY
@videoId = 1
@commentId = 4


// -> Comment
GET {{api}}/comment/{{videoId}}
###
POST {{api}}/comment/{{videoId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Hey this is a nicer comment"
}
###
PATCH  {{api}}/comment/{{commentId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Hey this is a nicer comment which is edited 2nd time"
}
###
DELETE  {{api}}/comment/{{commentId}}
Cookie: token={{token}}
###

# -> Comment: Reply
GET {{api}}/comment/reply/{{commentId}}
###
POST  {{api}}/comment/reply/{{commentId}}
Cookie: token={{token}}
Content-Type: application/json

{
    "text": "Reply 5 -3"
}
