@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.MQ.48rVlWZkUklvo69kDnVzudXUaFjVH1IVU7asr0ia7hI
@videoId = 1
@commentId = 1


// -> Rating: Video
GET {{api}}/ratings/videos/{{videoId}}
Cookie: token={{token}}
###
POST {{api}}/ratings/videos/{{videoId}}/like
Cookie: token={{token}}
###
POST {{api}}/ratings/videos/{{videoId}}/dislike
Cookie: token={{token}}
###
DELETE {{api}}/ratings/videos/{{videoId}}
Cookie: token={{token}}
###

// -> Rating: Comment
GET {{api}}/ratings/comments/{{commentId}}
Cookie: token={{token}}
###
POST {{api}}/ratings/comments/{{commentId}}/like
Cookie: token={{token}}
###
POST {{api}}/ratings/comments/{{commentId}}/dislike
Cookie: token={{token}}
###
DELETE {{api}}/ratings/comments/{{commentId}}
Cookie: token={{token}}
###