@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.NjA5ZGNmYTAwNzRhYjIxNmM4OWQ0YTY5.6BhYzzUTXry_3WHE2vVRwihQBXkqrSEnQdsi7zyYZ4g
@videoId = 609ea0a48d22892130792200
@commentId = 609ea7aba7107514dcdf5f14


// -> Rating: Video
GET {{api}}/rating/{{videoId}}?type=VIDEO
Cookie: token={{token}}
###
POST {{api}}/rating/{{videoId}}/like?type=VIDEO
Cookie: token={{token}}
###
POST {{api}}/rating/{{videoId}}/dislike?type=VIDEO
Cookie: token={{token}}
###
DELETE {{api}}/rating/{{videoId}}?type=VIDEO
Cookie: token={{token}}
###

// -> Rating: Comment
GET {{api}}/rating/{{commentId}}?type=COMMENT
Cookie: token={{token}}
###
POST {{api}}/rating/{{commentId}}/like?type=COMMENT
Cookie: token={{token}}
###
POST {{api}}/rating/{{commentId}}/dislike?type=COMMENT
Cookie: token={{token}}
###
DELETE {{api}}/rating/{{commentId}}?type=COMMENT
Cookie: token={{token}}
