@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.MQ.48rVlWZkUklvo69kDnVzudXUaFjVH1IVU7asr0ia7hI
@channelId = 1

GET {{api}}/subscription/{{channelId}}
Cookie: token={{token}}
###
POST {{api}}/subscription/{{channelId}}
Cookie: token={{token}}
###
DELETE {{api}}/subscription/{{channelId}}
Cookie: token={{token}}
###